name: "Deploy AWS"

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip Lambda Code
        run: |
          pwd
          ls -la
          cd app
          zip -r ../lambda_function.zip .

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file template.yml \
            --stack-name tech-challenger \
            --parameter-overrides \
              InstanceType=t2.micro \
              KeyName=my-key-pair \
            --capabilities CAPABILITY_IAM

      - name: Notify Deployment
        run: |
          echo "Deployment completed successfully!"
